version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "todo-plus"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "sdy9f8sdf9s8df89hsd"
      MYSQL_ROOT_PASSWORD: "root"
